export const AUTHENTIFICATION_SUCCESS = 'REGISTER_SUCCESS';
export const AUTHENTIFICATION_FAIL = 'REGISTER_FAIL';
export const ACCESS_ACCOUNT = 'ACCESS_ACCOUNT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';