const FETCH_SOURCES_REQUEST = 'FETCH_SOURCES_REQUEST';
const FETCH_SOURCES_SUCCESS = 'FETCH_SOURCES_SUCCESS';
const FETCH_SOURCES_FAILED = 'FETCH_SOURCES_FAILED';

export { FETCH_SOURCES_REQUEST, FETCH_SOURCES_SUCCESS, FETCH_SOURCES_FAILED };
